version: "3"

services:
  akyuu:
    image: "akyuu:latest"
    ports:
        - "80:4000"
    env_file:
        - rel/docker.env
    depends_on:
      - db

  db:
    image: groonga/pgroonga:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: unless-stopped
    volumes:
        - db-data:/var/lib/postgresql/data/pgdata

volumes:
    db-data:
